version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db          # Use service name 'db' to connect to MySQL container
      DB_USER: root        # Database user (root)
      DB_PASSWORD: root    # Password for root user
      DB_NAME: online_exam_portal_db  # Database name
    depends_on:
      - db  # Ensure the 'db' service starts before 'web'

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: online_exam_portal_db
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
